#!/bin/bash

echo "🔧 Setting up Vercel Blob Storage for File Uploads"
echo "=================================================="
echo ""

echo "📋 Step 1: Create Vercel Blob Storage"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your 'financny_page' project"
echo "3. Go to Settings → Storage"
echo "4. Click 'Create Database'"
echo "5. Choose 'Blob' (NOT Postgres - that's for database)"
echo "6. Follow the setup wizard"
echo "7. Copy the BLOB_READ_WRITE_TOKEN"
echo ""

echo "📋 Step 2: Add Blob Environment Variable"
echo "1. In Vercel Dashboard → Settings → Environment Variables"
echo "2. Add new variable:"
echo "   Name: BLOB_READ_WRITE_TOKEN"
echo "   Value: [paste your blob token]"
echo "   Environments: Production, Preview, Development"
echo ""

echo "📋 Step 3: Test Your Setup"
echo "After setting up the BLOB_READ_WRITE_TOKEN:"
echo "1. Redeploy your Vercel application (it will auto-deploy)"
echo "2. Go to your admin panel"
echo "3. Try uploading a blog post with an image"
echo "4. Check browser console for detailed error messages"
echo ""

echo "🔍 Troubleshooting:"
echo "- If you see 'Vercel Blob storage is not configured' → BLOB_READ_WRITE_TOKEN missing"
echo "- If you see 'Failed to upload to Vercel Blob storage' → Check blob storage quota/permissions"
echo "- For database issues → Make sure you ALSO have PostgreSQL set up (separate from Blob)"
echo ""

echo "✅ Both Required for Full Functionality:"
echo "1. PostgreSQL Database (for blog post data) → DATABASE_URL"
echo "2. Blob Storage (for image uploads) → BLOB_READ_WRITE_TOKEN"
